server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # All requests should go to index.html (for Angular routing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /backend/ {
      proxy_pass http://py-gke-django-svc:80/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
}
